name: Windows Server 2025 RDP

on: [push]

jobs:
  build:
    runs-on: windows-2025
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create user Matrix
        run: |
          net user Matrix Matrix#1234 /add
          net localgroup "Administrators" Matrix /add

      - name: Set Taskbar Defaults
        run: |
          REG LOAD HKLM\Default C:\Users\Default\NTUSER.DAT
          reg add "HKLM\Default\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v TaskbarAl /t REG_DWORD /d 0 /f
          reg add "HKLM\Default\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize" /v SystemUsesLightTheme /t REG_DWORD /d 0 /f
          reg add "HKLM\Default\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize" /v AppsUseLightTheme /t REG_DWORD /d 0 /f
          reg add "HKLM\Default\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize" /v EnableTransparency /t REG_DWORD /d 0 /f
          REG UNLOAD HKLM\Default

      - name: Setup Auto Apply Dark Theme on RDP Login
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path C:\Scripts -Force | Out-Null

          @'
          $wallpaperPath = "C:\Users\Matrix\Pictures\wallpaper.jpg"

          if (-not (Test-Path $wallpaperPath)) {
              Invoke-WebRequest -Uri "https://4kwallpapers.com/images/wallpapers/windows-11-dark-mode-blue-stock-official-3840x2160-5630.jpg" -OutFile $wallpaperPath
          }

          Start-Process "rundll32.exe" -ArgumentList 'themecpl.dll,OpenThemeAction C:\Windows\resources\Themes\dark.theme'
          reg add "HKCU\Control Panel\Desktop" /v Wallpaper /t REG_SZ /d $wallpaperPath /f
          RUNDLL32.EXE user32.dll,UpdatePerUserSystemParameters
          '@ | Out-File -FilePath C:\Scripts\ApplyDarkTheme.ps1 -Encoding UTF8

          $Action = New-ScheduledTaskAction -Execute "powershell.exe" -Argument "-ExecutionPolicy Bypass -File C:\Scripts\ApplyDarkTheme.ps1"
          $Trigger = New-ScheduledTaskTrigger -AtLogOn
          Register-ScheduledTask -Action $Action -Trigger $Trigger -TaskName "ApplyDarkTheme" -User "Matrix" -Force

      - name: Setup Auto Wallpaper on RDP Login
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path C:\Scripts -Force | Out-Null

          @'
          $ErrorActionPreference = "Stop"
          try {
              [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

              $artifactUrl = "https://gitlab.com/Shahzaib-YT/enigmano-windows-11-with-sound/-/raw/main/EnigMano.jpg"
              $themeDir    = "$env:APPDATA\Microsoft\Windows\Themes"
              $localPath   = Join-Path $themeDir "EnigMano.jpg"

              New-Item -Path $themeDir -ItemType Directory -Force | Out-Null

              if (Test-Path $localPath) { Remove-Item $localPath -Force }
              Invoke-WebRequest -Uri $artifactUrl -OutFile $localPath -UseBasicParsing

              Add-Type @"
                  using System.Runtime.InteropServices;
                  public class EnigManoVisual {
                      [DllImport("user32.dll", SetLastError = true)]
                      public static extern bool SystemParametersInfo(int uAction, int uParam, string lpvParam, int fuWinIni);
                  }
  "@
              Set-ItemProperty -Path "HKCU:\Control Panel\Desktop" -Name Wallpaper -Value $localPath
  Set-ItemProperty -Path "HKCU:\Control Panel\Desktop" -Name WallpaperStyle -Value 10
  Set-ItemProperty -Path "HKCU:\Control Panel\Desktop" -Name TileWallpaper -Value 0
  [EnigManoVisual]::SystemParametersInfo(0x0014, 0, $localPath, 0x0001 -bor 0x0002) | Out-Null
  }
  catch {
Write-Error "Wallpaper setup failed: $_"
  exit 1
}
  '@ | Out-File -FilePath C:\Scripts\SetWallpaper.ps1 -Encoding UTF8
  
  $Action  = New-ScheduledTaskAction -Execute "powershell.exe" -Argument "-ExecutionPolicy Bypass -File C:\Scripts\SetWallpaper.ps1"
  $Trigger = New-ScheduledTaskTrigger -AtLogOn
  Register-ScheduledTask -Action $Action -Trigger $Trigger -TaskName "SetWallpaper" -User "Matrix" -RunLevel Highest -Force

- name: Keep session alive
  run: |
    ping -t 127.0.0.1
