name: Testw

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025
    permissions:
      id-token: write # penting untuk OIDC
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Tailscale
        run: |
          Invoke-WebRequest -Uri https://pkgs.tailscale.com/stable/tailscale-setup-latest-amd64.msi -OutFile tailscale.msi
          Start-Process msiexec.exe -ArgumentList '/i tailscale.msi /quiet' -Wait

      - name: Start Tailscale
        run: |
          & "C:\Program Files\Tailscale\tailscale.exe" up --authkey "$env:TAILSCALE_AUTHKEY" --accept-routes
        env:
          TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}


      - name: Disable password complexity
        run: |
          secedit /export /cfg $env:TEMP\secpol.cfg
          (Get-Content $env:TEMP\secpol.cfg).Replace("PasswordComplexity = 1", "PasswordComplexity = 0") | Set-Content $env:TEMP\secpol.cfg
          secedit /configure /db $env:TEMP\secedit.sdb /cfg $env:TEMP\secpol.cfg /areas SECURITYPOLICY
          gpupdate /force

      - name: Create user Matrix
        run: |
          net user Matrix Matrix#1234 /add
          net localgroup "Administrators" Matrix /add

      - name: Reg
        run: |
          reg add "HKLM\SOFTWARE\Microsoft\Windows\DWM" /v ForceEffectMode /t REG_DWORD /d 2 /f
          reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v TaskbarAl /t REG_DWORD /f /d 0

      - name: Set Taskbar Defaults
        run: |
          REG LOAD HKLM\Default C:\Users\Default\NTUSER.DAT
          reg add "HKLM\Default\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v TaskbarAl /t REG_DWORD /d 0 /f
          REG UNLOAD HKLM\Default
      

          
      - name: Enable RDP
        run: |
          # Aktifkan RDP
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          # Izinkan lewat firewall
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          # Tambahkan user Matrix ke grup (tidak error jika sudah ada)
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "Matrix" -ErrorAction SilentlyContinue

      - name: ⚔️ Execute EnigMano Instance Script
        shell: pwsh
        run: |
          Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize" -Name "AppsUseLightTheme" -Value 0
          Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize" -Name "SystemUsesLightTheme" -Value 0
          $artifactUrl  = "https://4kwallpapers.com/images/wallpapers/windows-11-dark-mode-blue-stock-official-3840x2160-5630.jpg"
          $themeDir     = "$env:APPDATA\Microsoft\Windows\Themes"
          $localPath    = Join-Path $themeDir "Aero_Dark.jpg"
          
          New-Item -Path $themeDir -ItemType Directory -Force | Out-Null
          Invoke-WebRequest -Uri $artifactUrl -OutFile $localPath -UseBasicParsing
        

      - name: Keep session alive
        run: |
          Write-Output "Runner is alive. Press Ctrl+C to stop."
          while ($true) { Start-Sleep -Seconds 300 }
