name: Testw

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025
    permissions:
      id-token: write # penting untuk OIDC
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Tailscale
        run: |
          Invoke-WebRequest -Uri https://pkgs.tailscale.com/stable/tailscale-setup-latest-amd64.msi -OutFile tailscale.msi
          Start-Process msiexec.exe -ArgumentList '/i tailscale.msi /quiet' -Wait

      - name: Start Tailscale
        run: |
          & "C:\Program Files\Tailscale\tailscale.exe" up --authkey "$env:TAILSCALE_AUTHKEY" --accept-routes
        env:
          TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}


      - name: Disable password complexity
        run: |
          secedit /export /cfg $env:TEMP\secpol.cfg
          (Get-Content $env:TEMP\secpol.cfg).Replace("PasswordComplexity = 1", "PasswordComplexity = 0") | Set-Content $env:TEMP\secpol.cfg
          secedit /configure /db $env:TEMP\secedit.sdb /cfg $env:TEMP\secpol.cfg /areas SECURITYPOLICY
          gpupdate /force

      - name: Create user Matrix
        run: |
          net user Matrix Matrix#1234 /add
          net localgroup "Administrators" Matrix /add
          reg add "HKLM\SOFTWARE\Microsoft\Windows\DWM" /v ForceEffectMode /t REG_DWORD /d 2 /f
          rundll32.exe themecpl.dll,OpenThemeAction "C:\Windows\resources\Themes\dark.theme"


      - name: Ganti Wallpaper
        run: |
          $artifactUrl  = "https://4kwallpapers.com/images/wallpapers/windows-11-dark-mode-blue-stock-official-3840x2160-5630.jpg"
          $themeDir     = "$env:APPDATA\Microsoft\Windows\Themes"
          $localPath    = Join-Path $themeDir "Aero_Dark.jpg"
          
          New-Item -Path $themeDir -ItemType Directory -Force | Out-Null
          Invoke-WebRequest -Uri $artifactUrl -OutFile $localPath -UseBasicParsing
          
          Add-Type @"
          using System.Runtime.InteropServices;
          public class Wallpaper {
              [DllImport("user32.dll", SetLastError = true)]
              public static extern bool SystemParametersInfo(int uAction, int uParam, string lpvParam, int fuWinIni);
          }
          "@
          
          Set-ItemProperty -Path "HKCU:\Control Panel\Desktop" -Name Wallpaper -Value $localPath
          Set-ItemProperty -Path "HKCU:\Control Panel\Desktop" -Name WallpaperStyle -Value 6
          Set-ItemProperty -Path "HKCU:\Control Panel\Desktop" -Name TileWallpaper -Value 0
          
          [Wallpaper]::SystemParametersInfo(0x0014, 0, $localPath, 0x0001 -bor 0x0002) | Out-Null



      - name: Set Default User Profile (Taskbar + Dark Theme + Wallpaper)
        shell: pwsh
        run: |
          $url = "https://4kwallpapers.com/images/wallpapers/windows-11-dark-mode-blue-stock-official-3840x2160-5630.jpg"
          $wallpaperPath = "C:\Users\Default\Pictures\wallpaper.jpg"
      
          # Pastikan folder ada
          New-Item -ItemType Directory -Path (Split-Path $wallpaperPath) -Force | Out-Null
      
          # Download wallpaper
          Invoke-WebRequest -Uri $url -OutFile $wallpaperPath
      
          # Load Default User hive
          REG LOAD HKLM\Default C:\Users\Default\NTUSER.DAT
      
          # Taskbar kiri
          reg add "HKLM\Default\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v TaskbarAl /t REG_DWORD /d 0 /f
      
          # Dark theme (system + apps)
          reg add "HKLM\Default\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize" /v SystemUsesLightTheme /t REG_DWORD /d 0 /f
          reg add "HKLM\Default\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize" /v AppsUseLightTheme /t REG_DWORD /d 0 /f
      
          # Disable transparency
          reg add "HKLM\Default\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize" /v EnableTransparency /t REG_DWORD /d 0 /f
      
          # Set wallpaper
          reg add "HKLM\Default\Control Panel\Desktop" /v Wallpaper /t REG_SZ /d $wallpaperPath /f
      
          # Unload hive
          REG UNLOAD HKLM\Default



          
      - name: Enable RDP
        run: |
          # Aktifkan RDP
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          # Izinkan lewat firewall
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          # Tambahkan user Matrix ke grup (tidak error jika sudah ada)
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "Matrix" -ErrorAction SilentlyContinue

      - name: Setup Auto Apply Dark Theme on RDP Login
        shell: pwsh
        run: |
          # Buat folder script
          New-Item -ItemType Directory -Path C:\Scripts -Force | Out-Null
      
          # Simpan script ApplyDarkTheme.ps1
          @'
          $wallpaperPath = "C:\Users\Matrix\Pictures\wallpaper.jpg"
      
          if (-not (Test-Path $wallpaperPath)) {
              Invoke-WebRequest -Uri "https://4kwallpapers.com/images/wallpapers/windows-11-dark-mode-blue-stock-official-3840x2160-5630.jpg" -OutFile $wallpaperPath
          }
      
          Start-Process "rundll32.exe" -ArgumentList 'themecpl.dll,OpenThemeAction C:\Windows\resources\Themes\dark.theme'
          reg add "HKCU\Control Panel\Desktop" /v Wallpaper /t REG_SZ /d $wallpaperPath /f
          RUNDLL32.EXE user32.dll,UpdatePerUserSystemParameters
          '@ | Out-File -FilePath C:\Scripts\ApplyDarkTheme.ps1 -Encoding UTF8
      
          # Daftarkan Scheduled Task untuk user Matrix
          $Action = New-ScheduledTaskAction -Execute "powershell.exe" -Argument "-ExecutionPolicy Bypass -File C:\Scripts\ApplyDarkTheme.ps1"
          $Trigger = New-ScheduledTaskTrigger -AtLogOn
          Register-ScheduledTask -Action $Action -Trigger $Trigger -TaskName "ApplyDarkTheme" -User "Matrix" -Force



      - name: Keep session alive
        run: |
          Write-Output "Runner is alive. Press Ctrl+C to stop."
          while ($true) { Start-Sleep -Seconds 300 }
