name: Testw

on:
  #push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025
    permissions:
      id-token: write # penting untuk OIDC
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Tailscale
        run: |
          Invoke-WebRequest -Uri https://pkgs.tailscale.com/stable/tailscale-setup-latest-amd64.msi -OutFile tailscale.msi
          Start-Process msiexec.exe -ArgumentList '/i tailscale.msi /quiet' -Wait

      - name: Start Tailscale
        run: |
          & "C:\Program Files\Tailscale\tailscale.exe" up --authkey "$env:TAILSCALE_AUTHKEY" --accept-routes
        env:
          TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}


      - name: Disable password complexity
        run: |
          secedit /export /cfg $env:TEMP\secpol.cfg
          (Get-Content $env:TEMP\secpol.cfg).Replace("PasswordComplexity = 1", "PasswordComplexity = 0") | Set-Content $env:TEMP\secpol.cfg
          secedit /configure /db $env:TEMP\secedit.sdb /cfg $env:TEMP\secpol.cfg /areas SECURITYPOLICY
          gpupdate /force

      - name: Create user Matrix
        run: |
          net user Matrix Matrix#1234 /add
          net localgroup "Administrators" Matrix /add
          New-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows\DWM" -Name "ForceEffectMode" -Value 2 -PropertyType DWord
          #Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows\DWM" -Name "ForceEffectMode" -Value 2 -PropertyType DWord
          # Pindahkan Taskbar ke kiri
          Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" -Name "TaskbarAl" -Value 0
          
          # Nonaktifkan efek transparansi
          Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize" -Name "EnableTransparency" -Value 0



      - name: Enable RDP
        run: |
          # Aktifkan RDP
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          # Izinkan lewat firewall
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          # Tambahkan user Matrix ke grup (tidak error jika sudah ada)
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "Matrix" -ErrorAction SilentlyContinue

      - name: ⚔️ Execute EnigMano Instance Script
        shell: pwsh
        run: |
          powershell.exe
          Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize" -Name "AppsUseLightTheme" -Value 0
          Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize" -Name "SystemUsesLightTheme" -Value 0
          $artifactUrl  = "https://4kwallpapers.com/images/wallpapers/windows-11-dark-mode-blue-stock-official-3840x2160-5630.jpg"
          $themeDir     = "$env:APPDATA\Microsoft\Windows\Themes"
          $localPath    = Join-Path $themeDir "Aero_Dark.jpg"
          
          New-Item -Path $themeDir -ItemType Directory -Force | Out-Null
          Invoke-WebRequest -Uri $artifactUrl -OutFile $localPath -UseBasicParsing
          
          Add-Type @"
          using System.Runtime.InteropServices;
          public class Wallpaper {
              [DllImport("user32.dll", SetLastError = true)]
              public static extern bool SystemParametersInfo(int uAction, int uParam, string lpvParam, int fuWinIni);
          }
          "@
        
          Set-ItemProperty -Path "HKCU:\Control Panel\Desktop" -Name Wallpaper -Value $localPath
          Set-ItemProperty -Path "HKCU:\Control Panel\Desktop" -Name WallpaperStyle -Value 6
          Set-ItemProperty -Path "HKCU:\Control Panel\Desktop" -Name TileWallpaper -Value 0
          
          [Wallpaper]::SystemParametersInfo(0x0014, 0, $localPath, 0x0001 -bor 0x0002) | Out-Null

      - name: Keep session alive
        run: |
          Write-Output "Runner is alive. Press Ctrl+C to stop."
          while ($true) { Start-Sleep -Seconds 300 }
